=== DrSnowbird/amf/amf-client/shared/src/test/resources/production/myconnect-1.0.0-fat-raml/schema/payslips.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://schemas.asciano.com.au/json/v1/payslips",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "payslipId": {
                "type": "string"
            },
            "empId": {
                "description": "Employee ID of the employee the payslip belongs to",
                "type": "string"
            },
            "calendarGroupId": {
                "type": "string"
            },
            "gpSourceProduct": {
                "type": "string"
            },
            "paymentDate": {
                "type": "string",
                "format": "date"
            },
            "periodBeginDate": {
                "type": "string",
                "format": "date"
            },
            "periodEndDate": {
                "type": "string",
                "format": "date"
            },
            "grossPay": {
                "type": "number"
            },
            "netPay": {
                "type": "number"
            },
            "grossTax": {
                "type": "number"
            },
            "description": {
                "type": "string"
            }
        },
        "required": [ "payslipId" ],
        "additionalProperties": false
    },
    "additionalItems": false
}

=== DrSnowbird/amf/amf-client/shared/src/test/resources/production/myconnect-1.0.0-fat-raml/samples/payslip/payslips-example.json
[
    {
        "payslipId": "ps01",
        "empId": "1234",
        "calendarGroupId": "345",
        "gpSourceProduct": "gpSourceProduct01",
        "paymentDate": "2015-06-01",
        "periodBeginDate": "2015-05-01",
        "periodEndDate": "2015-06-30",
        "grossPay": 321.5,
        "netPay": 250,
        "grossTax": 71.5,
        "description": "May payslip"
    },
    {
        "payslipId": "ps01",
        "empId": "1234",
        "calendarGroupId": "345",
        "gpSourceProduct": "gpSourceProduct01",
        "paymentDate": "2015-06-01",
        "periodBeginDate": "2015-05-01",
        "periodEndDate": "2015-06-30",
        "grossPay": 321.5,
        "netPay": 250,
        "grossTax": 71.5,
        "description": "May payslip"
    }
]
