=== DrSnowbird/amf/amf-client/shared/src/test/resources/production/myconnect-1.0.0-fat-raml/schema/rosterchanges.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://schemas.asciano.com.au/json/v1/rosterchanges",
  "title": "Roster changes",
  "description": "Collection of roster changes",  
  "type": "array",
  "additionalItems": false,
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "rosterChangeType": {
        "type": "string"
      },
      "rosterChangeTypeDesc": {
        "type": "string"
      },
      "dateAppliedFor": {
        "type": "string",
        "format": "date"
      },
      "status": {
        "type": "string"
      }
    },
    "additionalProperties": false,
    "required": ["id"]
  }
}

=== DrSnowbird/amf/amf-client/shared/src/test/resources/production/myconnect-1.0.0-fat-raml/samples/rosterchanges/rosterchanges.json
[
  {
    "id": "R;2015-02-23;1",
    "rosterChangeType": "R",
    "rosterChangeTypeDesc": "RDO",
    "dateAppliedFor": "2015-02-23",
    "status": "Approved"
  },
  {
    "id": "R;2015-02-25;1",
    "rosterChangeType": "R",
    "rosterChangeTypeDesc": "RDO",
    "dateAppliedFor": "2015-02-25",
    "status": "Approved"
  }  
]
