=== DrSnowbird/amf/amf-client/shared/src/test/resources/production/myconnect-1.0.0-fat-raml/schema/submitleaveapplication.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://schemas.asciano.com.au/json/v1/submitleaveapplication",
    "title": "Leave application",
    "description": "Leave application data type",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "description": "One of the keys required to get an individual leave application"
        },
        "leaveTypeId": {
            "type": "string"
        },
        "startDate": {
            "type": "string",
            "format": "date"
        },
        "endDate": {
            "type": "string",
            "format": "date"
        },
        "leaveReason": {
            "type": "string"
        },
        "partialDays": {
            "enum": [ "None", "StartDayOnly", "EndDayOnly", "StartAndEnd", "All" ]
        },
        "startDayHours": {
            "type": "number"
        },
        "startDayHalfDay": {
            "type": "boolean"
        },
        "endDayHours": {
            "type": "number"
        },
        "endDayHalfDay": {
            "type": "boolean"
        },
        "allDayHours": {
            "type": "number"
        },
        "allDayHalfDay": {
            "type": "boolean"
        },
        "payInAdvance": {
            "type": "boolean"
        },
        "medicalCertificateProvided": {
            "type": "boolean"
        },
        "requesterComments": {
            "type": "string"
        },
        "attachment": {
            "type": "string"
        },
        "status": {
            "type": "string"
        }
    },
    "required": [ "startDate", "endDate" ],
    "additionalProperties": false
}

=== DrSnowbird/amf/amf-client/shared/src/test/resources/production/myconnect-1.0.0-fat-raml/samples/leave/submitleaveapplication-example.json
{
    "id": "123",
    "leaveTypeId": "1",
    "startDate": "2015-09-01",
    "endDate": "2015-09-15",
    "leaveReason": "ANL",
    "partialDays": "None",
    "startDayHours": 5,
    "startDayHalfDay": false,
    "endDayHours": 4,
    "endDayHalfDay": false,
    "allDayHours": 6,
    "allDayHalfDay": false,
    "payInAdvance": true,
    "medicalCertificateProvided": false,
    "requesterComments": "",
    "attachment": "",
    "status": ""
}
